package pt.ulisboa.tecnico.sdis.ws.cc;

import static javax.xml.ws.BindingProvider.ENDPOINT_ADDRESS_PROPERTY;

import java.util.List;
import java.util.Map;

import javax.xml.ws.BindingProvider;

import pt.ulisboa.tecnico.sdis.ws.CreditCard;
import pt.ulisboa.tecnico.sdis.ws.CreditCardImplService;

import pt.ulisboa.tecnico.sdis.ws.uddi.UDDINaming;

/**
 * Client port wrapper.
 *
 * Adds easier end point address configuration to the Port generated by
 * wsimport.
 */
public class CreditCardClient implements CreditCard {

	/** WS service */
	CreditCardImplService service = null;

	/** WS port (port type is the interface, port is the implementation) */
	CreditCard port = null;

	/** WS end point address */
	private static final String wsURL = "http://ws.sd.rnl.tecnico.ulisboa.pt:8080/cc";

	public String getWsURL() {
		return wsURL;
	}

	/** constructor with provided web service URL */
	public CreditCardClient() throws CreditCardClientException {
		createStub();
	}

	/** Stub creation and configuration */
	private void createStub() {
		System.out.println("Creating stub ...");
		service = new CreditCardImplService();
		port = service.getCreditCardImplPort();

		if (wsURL != null) {
			System.out.println("Setting endpoint address ...");
			BindingProvider bindingProvider = (BindingProvider) port;
			Map<String, Object> requestContext = bindingProvider.getRequestContext();
			requestContext.put(ENDPOINT_ADDRESS_PROPERTY, wsURL);
		}
	}

	// remote invocation methods ----------------------------------------------

	@Override
	public boolean validateNumber(String number) {
		return port.validateNumber(number);
	}

	// control operations -----------------------------------------------------

	@Override
	public String ping(String inputMessage) {
		return port.ping(inputMessage);
	}
	
}
